### PR TITLE
my css

### PR DESCRIPTION
**Pull request by fpsownage**
not counter-strike source but cascading style sheets

### CODE REVIEW

**Comment by KoolKidz112** [comment]
I changed some padding and changed the `px` measurements to `em`. You can look at my code if you want, I just switched around one of the class names and made the button look better

**Comment by KoolKidz112** [comment]
Lmk if you wanna add anything else or if this is O.K. to merge

**Comment by fpsownage** [comment]
Is fine.Tanks

**Comment by KoolKidz112** [comment]
Ok awesome. Merging .

**Comment by KoolKidz112** [comment]
Minor phuck up

**Pull request merged**
